DASHBOARD_HTML = r"""
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SoftGNN Dashboard</title>
<script src="https://unpkg.com/cytoscape@3.28.1/dist/cytoscape.min.js"></script>
<style>
:root{color-scheme:dark;--bg:#090b12;--card:rgba(20,24,38,.72);--line:rgba(148,163,184,.18);--text:#e5e7eb;--muted:#94a3b8;--cyan:#22d3ee;--violet:#a78bfa;--green:#34d399;--amber:#fbbf24;--red:#fb7185}*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui;background:radial-gradient(circle at top left,#172554,transparent 32%),radial-gradient(circle at bottom right,#4c1d95,transparent 28%),var(--bg);color:var(--text)}header{height:68px;display:flex;align-items:center;justify-content:space-between;padding:0 24px;border-bottom:1px solid var(--line);backdrop-filter:blur(18px)}h1{font-size:20px;margin:0}.pill{border:1px solid var(--line);padding:8px 12px;border-radius:999px;color:var(--muted)}main{display:grid;grid-template-columns:310px 1fr 340px;height:calc(100vh - 68px)}aside{padding:18px;border-right:1px solid var(--line);overflow:auto}.right{border-left:1px solid var(--line);border-right:0}.card{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:14px;margin-bottom:14px;box-shadow:0 20px 80px rgba(0,0,0,.22)}button,input,select{width:100%;border:1px solid var(--line);border-radius:12px;background:rgba(15,23,42,.8);color:var(--text);padding:10px 12px;margin:6px 0}button{cursor:pointer;background:linear-gradient(135deg,rgba(34,211,238,.18),rgba(167,139,250,.18));transition:.2s}button:hover{transform:translateY(-1px);border-color:var(--cyan)}button.write{background:linear-gradient(135deg,rgba(251,191,36,.22),rgba(251,113,133,.16))}#cy{height:100%;width:100%}.stats{display:grid;grid-template-columns:1fr 1fr;gap:10px}.stat{padding:12px;border-radius:14px;background:rgba(15,23,42,.68);border:1px solid var(--line)}.stat b{display:block;color:var(--cyan);font-size:22px}pre{white-space:pre-wrap;max-height:260px;overflow:auto;color:#cbd5e1}.muted{color:var(--muted);font-size:13px}.ok{color:var(--green)}.warn{color:var(--amber)}</style></head>
<body><header><h1>SoftGNN Interactive Graph</h1><div class="pill" id="status">Loading...</div></header><main>
<aside><div class="card"><h3>Actions</h3><button onclick="loadGraph()">Refresh Graph View</button><button onclick="runAction('scan')">Run Scan</button><button onclick="runAction('pr_scan')">Run PR Scan</button><button onclick="runImpact()">Run Impact for Selected</button><button class="write" onclick="runAction('refresh')">Refresh SoftGNN Memory</button><button class="write" onclick="runAction('map_runtime')">Map Runtime Coverage</button><button class="write" onclick="runGenerateFile()">Generate Selected File</button><button class="write" onclick="runGenerateTarget()">Generate Selected Node</button></div><div class="card"><h3>Focus</h3><input id="search" placeholder="Search node..." oninput="filterNodes()"><input id="focusFile" placeholder="src/foo.py"><button onclick="loadGraph({focus:document.getElementById('focusFile').value})">Focus File</button></div><div class="card"><h3>Live Logs</h3><pre id="logs">No jobs yet.</pre></div></aside>
<section id="cy"></section><aside class="right"><div class="card"><h3>Summary</h3><div class="stats" id="summary"></div></div><div class="card"><h3>Selected Node</h3><pre id="selected">Click a node.</pre></div></aside>
</main><script>
let cy=null, selected=null, graphData=null;
async function api(path, opts){const r=await fetch(path, opts); return await r.json();}
async function loadStatus(){const s=await api('/api/status'); document.getElementById('status').textContent=`${s.project} • ${s.branch||'no-git'} • ${s.head||''}`;}
function renderSummary(s){document.getElementById('summary').innerHTML=Object.entries(s).map(([k,v])=>`<div class="stat"><span>${k}</span><b>${v}</b></div>`).join('')}
async function loadGraph(params={}){const q=new URLSearchParams(params); graphData=await api('/api/graph?'+q); renderSummary(graphData.summary); const els=[...graphData.nodes.map(n=>({data:n})),...graphData.edges.map((e,i)=>({data:{id:'e'+i,...e}}))]; cy=cytoscape({container:document.getElementById('cy'),elements:els,style:[{selector:'node',style:{label:'data(label)',color:'#e5e7eb','background-color':e=>({File:'#22d3ee',Class:'#a78bfa',Function:'#34d399',TestFunction:'#fbbf24'}[e.data('type')]||'#64748b'),width:34,height:34,'font-size':10}},{selector:'edge',style:{width:1,'line-color':'#64748b','target-arrow-color':'#64748b','target-arrow-shape':'triangle','curve-style':'bezier',label:'data(type)','font-size':8,color:'#94a3b8'}}],layout:{name:'cose',animate:true}}); cy.on('tap','node',ev=>{selected=ev.target.data(); document.getElementById('selected').textContent=JSON.stringify(selected,null,2);});}
function filterNodes(){const q=document.getElementById('search').value.toLowerCase(); if(!cy)return; cy.nodes().forEach(n=>n.style('display',!q||JSON.stringify(n.data()).toLowerCase().includes(q)?'element':'none'))}
async function runAction(action, payload={}){if(['generate','generate_file','generate_target','refresh','map_runtime'].includes(action)&&!confirm(`Run ${action}?`))return; const job=await api('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})}); poll(job.job_id)}
function runImpact(){if(!selected)return alert('Select a node first'); runAction('impact',{target:selected.id})}
function runGenerateFile(){if(!selected)return alert('Select a file/function node first'); runAction('generate_file',{only_file:selected.source_file||selected.id.replace('FILE:','')})}
function runGenerateTarget(){if(!selected)return alert('Select a node first'); runAction('generate_target',{target:selected.id, source_file:selected.source_file})}
async function poll(id){const out=document.getElementById('logs'); const timer=setInterval(async()=>{const j=await api('/api/jobs/'+id); out.textContent=j.logs||''; if(j.done){clearInterval(timer); await loadGraph();}},1000)}
loadStatus(); loadGraph();
</script></body></html>
"""
